### ISSUE TITLE
cancel_order çalışmıyor.

### ISSUE THREAD

**Issue by yusufilker** [BTCTrader/broker-api-docs#299]
`btcturk.create_order('LINK/TRY', 'stopLimit', 'buy', 1, 110, 109)`     komutu çalışıyor ve emir veriliyor.
`print(clientp.get_open_orders("LINKTRY"))`    çalışıyor ve çıktısı şöyle: 

```
{
  "data": {
    "asks": [],
    "bids": [
      {
        "id": 671533370,
        "price": "110.00",
        "amount": "1.00",
        "quantity": "1.00",
        "stopPrice": "109.00",
        "pairSymbol": "LINKTRY",
        "pairSymbolNormalized": "LINK_TRY",
        "type": "buy",
        "method": "stoplimit",
        "orderClientId": "f23s7ee5-6dm0-4c05-9692-4f06fe72d33e",
        "time": 0,
        "updateTime": 1605157735153,
        "status": "Untouched",
        "leftAmount": "1.00"
      }
    ]
  },
  "success": true,
  "message": null,
  "code": 0
}
```

buraya kadar sorun yok, ancak "id": 671533370  ile cancel_order çalıştırdığımda aşağıdaki hatayı alıyorum:
`print(clientp.cancel_order(671533370))`

`btcturk DELETE https://api.btcturk.com/api/v1/order 400 Bad Request {"success":false,"message":"NO_ORDER_MATCHES_YOUR_REQUEST","code":1052}`

    def cancel_order(self, order_id):
        data = {"id": order_id}
        return self._make_request_p(method="DELETE", path="order", data=data)

`
ccxt:
`
    def cancel_order(self, id, symbol=None, params={}):
        request = {
            'id': id,
        }
        return self.privateDeleteOrder(self.extend(request, params))
``

orderClientId yi de denedim sonuç aynı oldu.  REST API DELETE sadece cancel_order komutunda var,  DELETE  çalışıyor değil mi? API dökümantasyonunda hata var mıdır? yardımcı olursanız sevinirim.

bu arada yukarıdaki bazı kodlar ccxt den bazıları ise başka bir github repo dan.
her iki kodu da temizliyorum, büyük oranda her ikisi de public-private uçlarda çalışıyor. 
cancel_order fonksiyonları her ikisinde de çalışmıyor. diğerlerine göre bu kadar basit bir fonksiyon  neden çalışmaz anlamadım.

**Comment by ocengiz0** [comment]
@yusufilker order_id'yi string olarak gondermeyi denediniz mi?

**Comment by yusufilker** [comment]
şu şekilde denedim ancak sorun devam ediyor.  print(request['id'])  de doğru id consola yazılıyor, burada problem yok.

```
    def cancel_order(self, id, params={}):
        request = {
            'id': str(id),
        }
        print(request['id'])
        return self.privateDeleteOrder(self.extend(request, params))
```

hata mesajı:
```

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 588, in fetch
    response.raise_for_status()
  File "C:\Python39\lib\site-packages\requests\models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.btcturk.com/api/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yusuf\python\trader\ccxt\ilk.py", line 34, in <module>
    print (btcturk.cancel_order('674400185'))                                      # çalışmıyor
  File "C:\Python39\lib\site-packages\ccxt\btcturk.py", line 300, in cancel_order
    return self.privateDeleteOrder(self.extend(request, params))
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 465, in inner
    return entry(_self, **inner_kwargs)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 490, in request
    return self.fetch2(path, api, method, params, headers, body)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 486, in fetch2
    return self.fetch(request['url'], request['method'], request['headers'], request['body'])
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 605, in fetch
    self.handle_http_status_code(http_status_code, http_status_text, url, method, http_response)
  File "C:\Python39\lib\site-packages\ccxt\base\exchange.py", line 636, in handle_http_status_code
    raise Exception(' '.join([self.id, method, url, string_code, http_status_text, body]))
ccxt.base.errors.ExchangeNotAvailable: btcturk DELETE https://api.btcturk.com/api/v1/order 400 Bad Request {"success":false,"message":"NO_ORDER_MATCHES_YOUR_REQUEST","code":1052}

```

**Comment by ocengiz0** [comment]
Python icin ornek bi repo var, inceleyin derim

https://github.com/erhan/pybtcturk/blob/master/btcturk/btcturk.py

**Comment by onurgozupek** [comment]
Pyhton'da emir iptali için şu örnek kodu kullanabilirsiniz:

```python

def authenticate():
        public_key = API_KEY
        private_key = API_SECRET
        private_key = base64.b64decode(private_key)
        stamp = str(int(time.time())*1000)
        data = "{}{}".format(public_key , stamp).encode('utf-8')
        signature = hmac.new(private_key , data , hashlib.sha256).digest()
        signature = base64.b64encode(signature)
        headers = {"X-PCK":public_key , "X-Stamp":stamp , "X-Signature":signature , "Content-Type":"application/json"}
        return headers

def cancelOrder(orderId):
        url = "https://api.btcturk.com/api/v1/order"
        params = {"id":orderId}
        resp = requests.delete(url=url , headers=authenticate() , params=params)
        if resp.status_code == 200:
            result = resp.json()
            if result['success'] == True:
                return "Order Deleted: " + str(orderId)
        else:
            return "Error deleting order. Status code",resp.status_code

cancelOrder(12345678)

```

**Comment by yusufilker** [comment]
ok teşekkürler

**Comment by emreacar** [comment]
Merhaba aynı hatayı ben de alıyorum.  id parametresini hem string hem number olarak ilettim ama sonuç aynı. 

Öncelikle açık emirleri çekiyorum dönen sonuç şu şekilde;

```
ORDERS {
  asks: [
    {
      id: 3028496980,
      price: '100.00',
      amount: '1.38',
      quantity: '1.38',
      stopPrice: '0.00',
      pairSymbol: 'EOSTRY',
      pairSymbolNormalized: 'EOS_TRY',
      type: 'sell',
      method: 'limit',
      orderClientId: 'advanced',
      time: 0,
      updateTime: 1620514400663,
      status: 'Untouched',
      leftAmount: '1.38'
    }
  ],
  bids: []
}
```

Daha sonra listeden açık emrin id değerini emri silmek için gönderiyorum.
```
Request (id as string) {
    url: '/api/v1/order',
    method: 'delete',
    baseURL: 'https://api.btcturk.com',
    id: '3028496980',
}

Request (id as number) {
    url: '/api/v1/order',
    method: 'delete',
    baseURL: 'https://api.btcturk.com',
    id: 3028496980,
}

Response {
  success: false,
  message: 'NO_ORDER_MATCHES_YOUR_REQUEST',
  code: 1052
}
```
