### ISSUE TITLE
SSLError Hatasi ve Sebebi

### ISSUE THREAD

**Issue by emirhanyasin** [BTCTrader/broker-api-docs#454]
Traceback (most recent call last):
  File "/home/coco/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/coco/lib/python3.7/site-packages/urllib3/connectionpool.py", line 449, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/coco/lib/python3.7/site-packages/urllib3/connectionpool.py", line 444, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1373, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.7/ssl.py", line 1071, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.7/ssl.py", line 929, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coco/lib/python3.7/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/coco/lib/python3.7/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/coco/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.btcturk.com', port=443): Max retries exceeded with url: /api/v1/order (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Binance-BtcTurk-Quoter/quoter-v2.2/quoter_tuned.py", line 479, in run_quoter
    quoter.quoter()
  File "/home/Binance-BtcTurk-Quoter/quoter-v2.2/quoter_tuned.py", line 345, in quoter
    pair_symbol = btcturk_symbol
  File "/home/coco/lib/python3.7/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/home/coco/lib/python3.7/site-packages/btcturk_api/client.py", line 1309, in submit_limit_order
    return self._submit_order(params)
  File "/home/coco/lib/python3.7/site-packages/btcturk_api/properties.py", line 11, in wrapper_decorator
    value = func(*args, **kwargs)
  File "/home/coco/lib/python3.7/site-packages/btcturk_api/client.py", line 1437, in _submit_order
    return self._post(request_url, params)
  File "/home/coco/lib/python3.7/site-packages/btcturk_api/client.py", line 384, in _post
    response = self.session.post(url=url, data=json.dumps(params))
  File "/home/coco/lib/python3.7/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/coco/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/coco/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/coco/lib/python3.7/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.btcturk.com', port=443): Max retries exceeded with url: /api/v1/order (Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)')))

Merhabalar,

Ayni anda birden fazla coinde islem yaparken, bazi coinlere attigim emirlerden yukarida paylasmis oldugum hatayi aliyorum. Bu hatanin sebebi ve cozum yoluyla ilgili goruslerinizi paylasirsaniz sevinirim. 

Tesekkurler

**Comment by suleymanbyzt** [comment]
Selamlar,

İnternetinizle ilgili sorun yaşamanıza bağlı olarak `(Caused by SSLError(SSLError(1, '[SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2570)'` hatası alabilirsiniz. 
Bağlantı türünüzü değiştirmeniz durumunda bu sorunla karşılaşmayacaksınız. Wifi ile bağlantı sağlıyorsanız bunu ethernet girişi yapabilir ya da wifi bağlantı ayarlarınızı düzenleyebilirsiniz. 

Ayrıca internetinizde yaşanacak bu gibi sorunlar nedeniyle bağlantının kopmaması adına yeniden deneme sayısını yükseltip, her yeni denemede aralara time sleep ekleyebilirsiniz. İnternet hizmetinizde sorun olması durumunda server'dan gelen paketlerin doğru indirilmemesine bağlı olarak bu gibi hatalardan kaçınmak adına bu adımları izleyebilirsiniz.

**Comment by emirhanyasin** [comment]
Merhaba,

Interneti ethernet girisi uzerinden kablolu fiber kullaniyorum. Baglanti sorunu olmadigi durumlarda da (kopma, kablosal sikinti, baglanti kesintisi vs.) bu hatayi aliyorum. 

Bahsettiginiz internet kaynakli problem nedir? Bu durumda ne oneriyorsunuz? Requestleri try/except bloklari icinde gondermeme ragmen bu hata processin calismasini durduruyor. Bunu handle etmenin bir cozumu var mi?

Tesekkurler

**Comment by suleymanbyzt** [comment]
Merhaba,

```python
import time

while True:
    try:
        # code
    
    except:
        # message
    
    finally:
        time.sleep(5)
```

While döngüsüne alarak finally için time.sleep eklemesi yapabilirsiniz. while loop değeri manuel olarak true olarak düzenlendiği için siz uygulamayı kapatana kadar loop çalışacaktır.
